#[derive(Debug, Hash, PartialEq, Eq, PartialOrd, Ord, Clone, Copy)]
#[repr(u8)]
pub enum MouseButton {
    Left = 0,
    Right = 1,
    Middle = 2,
    Back = 3,
    Forward = 4,
    Button6 = 5,
    Button7 = 6,
    Button8 = 7,
    Button9 = 8,
    Button10 = 9,
    Button11 = 10,
    Button12 = 11,
    Button13 = 12,
    Button14 = 13,
    Button15 = 14,
    Button16 = 15,
    Button17 = 16,
    Button18 = 17,
    Button19 = 18,
    Button20 = 19,
    Button21 = 20,
    Button22 = 21,
    Button23 = 22,
    Button24 = 23,
    Button25 = 24,
    Button26 = 25,
    Button27 = 26,
    Button28 = 27,
    Button29 = 28,
    Button30 = 29,
    Button31 = 30,
    Button32 = 31,
}

impl MouseButton {
    pub fn try_from_u8(b: u8) -> Option<MouseButton> {
        Some(match b {
            0 => MouseButton::Left,
            1 => MouseButton::Right,
            2 => MouseButton::Middle,
            3 => MouseButton::Back,
            4 => MouseButton::Forward,
            5 => MouseButton::Button6,
            6 => MouseButton::Button7,
            7 => MouseButton::Button8,
            8 => MouseButton::Button9,
            9 => MouseButton::Button10,
            10 => MouseButton::Button11,
            11 => MouseButton::Button12,
            12 => MouseButton::Button13,
            13 => MouseButton::Button14,
            14 => MouseButton::Button15,
            15 => MouseButton::Button16,
            16 => MouseButton::Button17,
            17 => MouseButton::Button18,
            18 => MouseButton::Button19,
            19 => MouseButton::Button20,
            20 => MouseButton::Button21,
            21 => MouseButton::Button22,
            22 => MouseButton::Button23,
            23 => MouseButton::Button24,
            24 => MouseButton::Button25,
            25 => MouseButton::Button26,
            26 => MouseButton::Button27,
            27 => MouseButton::Button28,
            28 => MouseButton::Button29,
            29 => MouseButton::Button30,
            30 => MouseButton::Button31,
            31 => MouseButton::Button32,
            _ => return None,
        })
    }
}
